### ISSUE TITLE
Printing password in toString (are you in your senses?)

### ISSUE THREAD

**Issue by pkt1583** [DevvratPandey/SpringBootApplication#8]
https://github.com/DevvratPandey/SpringBootApplication/blob/3fb7bbff13ab2d04f70994de33da0d3e7f6e8f85/springbootrest/src/main/java/com/springbootrest/springbootrest/services/UserServiceImpl.java#L17

Remove printing password

**Comment by DevvratPandey** [comment]
The issue has been resolved
